<?php

return [
    'category_tags' => [
        'makanan utama' => [
            'pedas',
            'gurih',
            'manis',
            'asam',
            'berkuah',
            'kering',
            'mengenyangkan',
            'ringan',
            'nasi',
            'mie',
            'ayam',
            'daging',
            'seafood',
            'sayur',
            'sarapan',
            'makan_siang',
            'makan_malam',
            'ramah_anak',
            'sharing_bersama',
        ],
        'minuman' => [
            'manis',
            'segar',
            'dingin',
            'hangat',
            'creamy',
            'kopi',
            'teh',
            'susu',
            'coklat',
            'buah',
            'less_sugar',
            'tanpa_gula',
            'ramah_anak',
            'cocok_siang',
            'cocok_malam',
            'cocok_cuaca_panas',
        ],
        'cemilan' => [
            'pedas',
            'gurih',
            'manis',
            'asin',
            'renyah',
            'lembut',
            'kering',
            'gorengan',
            'snack',
            'ringan',
            'mengenyangkan',
            'sharing_bersama',
            'cocok_ngemil',
            'cocok_santai',
            'cocok_sore',
            'ramah_anak',
        ],
    ],

    'category_metadata' => [
        'makanan utama' => ['spice_level', 'sweet_level', 'calorie_level', 'tags'],
        'minuman' => ['sweet_level', 'fresh_level', 'calorie_level', 'tags'],
        'cemilan' => ['spice_level', 'sweet_level', 'calorie_level', 'tags'],
    ],

    // Backward compatibility for components/services that still read a flat tag list.
    'allowed_tags' => [
        'pedas',
        'gurih',
        'manis',
        'asam',
        'berkuah',
        'kering',
        'mengenyangkan',
        'ringan',
        'nasi',
        'mie',
        'ayam',
        'daging',
        'seafood',
        'sayur',
        'sarapan',
        'makan_siang',
        'makan_malam',
        'ramah_anak',
        'sharing_bersama',
        'segar',
        'dingin',
        'hangat',
        'creamy',
        'kopi',
        'teh',
        'susu',
        'coklat',
        'buah',
        'less_sugar',
        'tanpa_gula',
        'cocok_siang',
        'cocok_malam',
        'cocok_cuaca_panas',
        'asin',
        'renyah',
        'lembut',
        'gorengan',
        'snack',
        'cocok_ngemil',
        'cocok_santai',
        'cocok_sore',
        // Legacy alias.
        'cocok_berbagi',
    ],

    // Keep lowercase values for backward compatibility in existing chatbot filters.
    'calorie_levels' => ['low', 'medium', 'high'],

];
